name: "mace_finetuning"
model: "MACE"
foundation_model: "small"
stress_weight: 0.0
forces_weight: 0.0
energy_weight: 1.0
multiheads_finetuning: False
model_dir: "MACE_models_MP"
log_dir: "MACE_models_MP"
checkpoints_dir: "MACE_models_MP"
results_dir: "MACE_models_MP"
train_file: "../datasets/tmQM_X1_split_05112025/tmQM_X1_train.xyz"
valid_file: "../datasets/tmQM_X1_split_05112025/tmQM_X1_val.xyz"
test_file: "../datasets/tmQM_X1_split_05112025/tmQM_X1_test.xyz"
energy_key: "REF_energy"
E0s: average 
device: cuda
batch_size: 16
max_num_epochs: 10
swa: True
seed: 345
